# Analysis of Access, Equity, and Diversity in MBA Admissions

### Loading the Dataset and Checking for Missing Values
In this section, we load the MBA Admissions dataset into a Pandas DataFrame and check for missing values to understand the completeness of our data.

In [1]:
import pandas as pd       # for data manipulation
import numpy as np        # for numerical operations
import matplotlib.pyplot as plt  # for plotting
import seaborn as sns     # for advanced visualizations
from ydata_profiling import ProfileReport

In [2]:
import os
base_dir = os.getcwd()
file_path = os.path.join(base_dir, "Data", "MBA.csv")

df = pd.read_csv(file_path)
df.head()

,application_id,gender,international,gpa,major,race,gmat,work_exp,work_industry,admission
0,1,Female,False,3.30,Business,Asian,620.0,3.0,Financial Services,Admit
1,2,Male,False,3.28,Humanities,Black,680.0,5.0,Investment Management,NaN
2,3,Female,True,3.30,Business,NaN,710.0,5.0,Technology,Admit
3,4,Male,False,3.47,STEM,Black,690.0,6.0,Technology,NaN
4,5,Male,False,3.35,STEM,Hispanic,590.0,5.0,Consulting,NaN

In [3]:
import os
print("Fichiers dans le dossier Data :", os.listdir("Data"))

Fichiers dans le dossier Data : ['MBA.csv', 'MBA_admissions_final.csv']

In [4]:
# Check the missing values
df.isnull().sum()

application_id       0
gender               0
international        0
gpa                  0
major                0
race              1842
gmat                 0
work_exp             0
work_industry        0
admission         5194
dtype: int64

### Data Cleaning Notes

According to the dataset documentation:

- In the `admission` column, null values represent **Denied** applications. We will fill these nulls with "Deny" to make our analysis clearer and more consistent.
- In the `race` column, null values correspond to **international students**. We will fill these nulls with "International" to simplify our categorical analysis.

In [5]:
# Replace nulls in 'admission' with 'Deny' and nulls in race  with international
df["admission"]=df["admission"].fillna("Deny")
df["race"]=df["race"].fillna("International")
df.isnull().sum()

application_id    0
gender            0
international     0
gpa               0
major             0
race              0
gmat              0
work_exp          0
work_industry     0
admission         0
dtype: int64

### Statistics

In [6]:
# Summary statistics for numeric columns
df[['gpa', 'gmat', 'work_exp']].describe()

               gpa         gmat     work_exp
count  6194.000000  6194.000000  6194.000000
mean      3.250714   651.092993     5.016952
std       0.151541    49.294883     1.032432
min       2.650000   570.000000     1.000000
25%       3.150000   610.000000     4.000000
50%       3.250000   650.000000     5.000000
75%       3.350000   680.000000     6.000000
max       3.770000   780.000000     9.000000

In [7]:

# Categorical columns
categorical_cols = ['gender', 'international', 'major', 'race', 'work_industry', 'admission']
for col in categorical_cols:
    print(df[col].value_counts(normalize=True) * 100)
    print("\n")

gender
Male      63.658379
Female    36.341621
Name: proportion, dtype: float64


international
False    70.261543
True     29.738457
Name: proportion, dtype: float64


major
Humanities    40.054892
STEM          30.271230
Business      29.673878
Name: proportion, dtype: float64


race
International    29.738457
White            23.506619
Asian            18.517921
Black            14.788505
Hispanic          9.622215
Other             3.826284
Name: proportion, dtype: float64


work_industry
Consulting               26.138198
PE/VC                    14.643203
Technology               11.559574
Nonprofit/Gov            10.510171
Investment Banking        9.363901
Financial Services        7.281240
Other                     6.796900
Health Care               5.392315
Investment Management     2.680013
CPG                       1.840491
Real Estate               1.792057
Media/Entertainment       0.952535
Retail                    0.532774
Energy                    0.516629
Name: proportion, dtype: float64


admission
Deny        83.855344
Admit       14.530191
Waitlist     1.614466
Name: proportion, dtype: float64

### Transforming Work Experience, gpa and gmat  into Categories

In [8]:
# Create exp_group bins 
df["work_exp_group"] = pd.cut(
    df["work_exp"],
    bins=[0, 3, 6, 10],        
    labels=["1-3 years", "4-6 years", "7+ years"]
)
# Check the transformation
print(df["work_exp_group"].value_counts().sort_index())

work_exp_group
1-3 years     403
4-6 years    5384
7+ years      407
Name: count, dtype: int64

In [9]:
# Create gmat_group bins
df["gmat_group"] = pd.cut(
    df["gmat"],
    bins=[550, 600, 650, 700, 750, 800],
    labels=[
        "550–599",
        "600–649",
        "650–699",
        "700–749",
        "750–800"
    ]
)
#Check the transformation
print(df["gmat_group"].value_counts().sort_index())

gmat_group
550–599    1207
600–649    2132
650–699    1945
700–749     754
750–800     156
Name: count, dtype: int64

In [10]:
#Create gpa_group bins 
df["gpa_group"] = pd.cut(
    df["gpa"],
    bins=[2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00],
    labels=[
        "2.50–2.74",
        "2.75–2.99",
        "3.00–3.24",
        "3.25–3.49",
        "3.50–3.74",
        "3.75–4.00"
    ]
)
#Check the transformation 
print(df["gpa_group"].value_counts().sort_index())

gpa_group
2.50–2.74       3
2.75–2.99     324
3.00–3.24    2845
3.25–3.49    2732
3.50–3.74     287
3.75–4.00       3
Name: count, dtype: int64

### Distribution

In [11]:
# Race distribution
race_counts = df['race'].value_counts(normalize=True) * 100
print("Percentage of applicants by race:")
print(race_counts.round(2))
print("\n")

# major distribution
major_counts = df['major'].value_counts(normalize=True) * 100
print("Percentage of applicants by major:")
print(major_counts.round(2))
print("\n")
# Industry distribution
work_industry_counts = df['work_industry'].value_counts(normalize=True) * 100
print("Percentage of applicants by industry:")
print(work_industry_counts.round(2))
print("\n")

# Gender distribution
gender_counts = df['gender'].value_counts(normalize=True) * 100
print("Percentage of applicants by gender:")
print(gender_counts.round(2))
print("\n")

# international distribution
intl_counts = df['international'].value_counts(normalize=True) * 100
print("Percentage of applicants by international status:")
print(intl_counts.round(2))

Percentage of applicants by race:
race
International    29.74
White            23.51
Asian            18.52
Black            14.79
Hispanic          9.62
Other             3.83
Name: proportion, dtype: float64


Percentage of applicants by major:
major
Humanities    40.05
STEM          30.27
Business      29.67
Name: proportion, dtype: float64


Percentage of applicants by industry:
work_industry
Consulting               26.14
PE/VC                    14.64
Technology               11.56
Nonprofit/Gov            10.51
Investment Banking        9.36
Financial Services        7.28
Other                     6.80
Health Care               5.39
Investment Management     2.68
CPG                       1.84
Real Estate               1.79
Media/Entertainment       0.95
Retail                    0.53
Energy                    0.52
Name: proportion, dtype: float64


Percentage of applicants by gender:
gender
Male      63.66
Female    36.34
Name: proportion, dtype: float64


Percentage of applicants by international status:
international
False    70.26
True     29.74
Name: proportion, dtype: float64

### Analysis

In [12]:
# Admission Rate by gender
gender_admission = pd.crosstab(df["gender"], df["admission"], normalize="index") * 100
print("Admission Rate by Gender (%) ")
display(gender_admission.round(2))

Admission Rate by Gender (%)

admission  Admit   Deny  Waitlist
gender
Female     19.99  77.79      2.22
Male       11.41  87.32      1.27

In [13]:
# Admission Rate by Major
major_admission = pd.crosstab(df["major"], df["admission"], normalize="index")*100
print("Admission Rate  by Major (%)")
(major_admission.round(2))

Admission Rate  by Major (%)

admission   Admit   Deny  Waitlist
major
Business    14.69  84.11      1.20
Humanities  14.79  83.56      1.65
STEM        14.03  84.00      1.97

In [14]:
# Admission Rate by race
race_admission=pd.crosstab(df["race"], df["admission"], normalize="index")*100
print("Admission Rate by Race (%)")
display(race_admission.round(2))

Admission Rate by Race (%)

admission      Admit   Deny  Waitlist
race
Asian          16.56  81.52      1.92
Black           8.73  90.17      1.09
Hispanic       10.40  88.26      1.34
International  15.09  83.28      1.63
Other          19.41  78.90      1.69
White          16.76  81.46      1.79

In [15]:
#Admission Rate by work-industry
work_industry_admission=pd.crosstab(df["work_industry"], df["admission"], normalize="index")*100
print("Admission Rate by work_industry (%)")
display(work_industry_admission)

Admission Rate by work_industry (%)

admission                  Admit       Deny  Waitlist
work_industry
CPG                    17.543860  81.578947  0.877193
Consulting             13.835701  84.126004  2.038295
Energy                  9.375000  90.625000  0.000000
Financial Services     19.068736  78.935698  1.995565
Health Care            11.976048  85.628743  2.395210
Investment Banking     14.137931  84.482759  1.379310
Investment Management  21.686747  77.710843  0.602410
Media/Entertainment    11.864407  84.745763  3.389831
Nonprofit/Gov          13.671275  84.946237  1.382488
Other                  13.539192  85.035629  1.425178
PE/VC                  13.450937  85.115766  1.433297
Real Estate            16.216216  82.882883  0.900901
Retail                 12.121212  84.848485  3.030303
Technology             15.642458  83.240223  1.117318

In [16]:
# Admission rate by work_exp_group
admission_work_exp_group= pd.crosstab(df["work_exp_group"], df["admission"], normalize="index")*100
print("Admission by Work_exp")
display(admission_work_exp_group)

Admission by Work_exp

admission           Admit       Deny  Waitlist
work_exp_group
1-3 years       14.640199  83.374690  1.985112
4-6 years       14.598811  83.766716  1.634473
7+ years        13.513514  85.503686  0.982801

In [17]:
# Mean of gpa and gmat of admssion statut
df1=df.groupby("admission")[["gpa", "gmat"]].mean().round(5)
df1

               gpa       gmat
admission
Admit      3.35487  692.73333
Deny       3.23146  643.44436
Waitlist   3.31350  673.60000

In [18]:
# Mean of GPA and GMAT
mean_gpa = df['gpa'].mean()
mean_gmat = df['gmat'].mean()
mean_exp = df["work_exp"].mean()

print(f"Mean GPA: {mean_gpa:.2f}")
print(f"Mean GMAT: {mean_gmat:.2f}")
print(f"Mean work_exp:{mean_exp:.2f}")

Mean GPA: 3.25
Mean GMAT: 651.09
Mean work_exp:5.02

In [19]:
print(df.dtypes)
print("\n")
print(df.shape)

application_id       int64
gender              object
international         bool
gpa                float64
major               object
race                object
gmat               float64
work_exp           float64
work_industry       object
admission           object
work_exp_group    category
gmat_group        category
gpa_group         category
dtype: object


(6194, 13)

### Exporting the Final Dataset for Power BI

In [20]:
# Get current working directory
base_dir = os.getcwd()

# Path for output file inside Data folder
output_path = os.path.join(base_dir, "Data", "MBA_admissions_final.csv")

# Export the DataFrame without index
df.to_csv(output_path, index=False)